# Generated by Django 6.0.2 on 2026-02-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('tenant', 'tenant')], default='tenant', max_length=10),
            preserve_default=False,
        ),
    ]
