# Generated by Django 6.0.2 on 2026-02-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], default='tenant', max_length=10),
        ),
    ]
