# Generated by Django 6.0.2 on 2026-04-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
