# Generated by Django 6.0.2 on 2026-02-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='move_in_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='amount',
            new_name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
        migrations.AddField(
            model_name='booking',
            name='security_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
