# Generated by Django 6.0.2 on 2026-02-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_delete_propertypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(default='properties/default.jpg', upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
