# Generated by Django 6.0.2 on 2026-04-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_room_ac_room_parking_room_room_type_room_wifi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='room',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='wifi',
        ),
    ]
